booking/urls.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.urls import path
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app_name = 'booking'
urlpatterns = [
    path('user-panel/', views.user_panel, name='user-panel'),
    path('booking_form/', views.booking_new, name='booking-form'),
    path('booking-edit/<int:booking_id>',
         views.booking_edit,
         name='edit-booking'),
    path('booking-delete/<int:id>',
         views.booking_delete,
         name='delete-booking'),

]

contact/urls.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.urls import path
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app_name = 'contact'
urlpatterns = [
    path('contact/', views.ContactMessage.as_view(), name='contact'),
]

dragonsflagon/urls.py
from django.contrib import admin
from django.urls import path, include
from tavern import views, urls
from booking import views, urls
from events import views, urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('tavern.urls'), name='tavern_urls'),
    path('booking/', include('booking.urls'), name='booking_urls'),
    path('contact/', include('contact.urls'), name='contact_urls'),
    path('events/', include('events.urls'), name='events_urls'),
    path('accounts/', include('allauth.urls')),
]

events/urls.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.conf.urls import url
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

app_name = 'events'
urlpatterns = [
   url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
   url(r'^event/new/$', views.event_new, name='event_new'),
   url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
   url(r'^event/delete/(?P<event_id>\d+)/$',
       views.event_delete,
       name='event_delete'),
]

booking/models.py
# Create your models here.
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SERVICE_CHOICES = (
    ("Drinks", "Drinks"),
    ("Food and Drinks", "Food and Drinks"),
    ("Board Game Session", "Board Game Session"),
    ("Food, Drinks and Games", "Food, Drinks and Games"),
    )

TIME_CHOICES = (
    ("12 PM", "12 PM"),
    ("1 PM", "1 PM"),
    ("2 PM", "2 PM"),
    ("3 PM", "3 PM"),
    ("4 PM", "4 PM"),
    ("5 PM", "5 PM"),
    ("6 PM", "6 PM"),
    ("7 PM", "7 PM"),
    ("8 PM", "8 PM"),
    ("9 PM", "9 PM"),
)


class TableBooking(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )
    email = models.EmailField()
    service = models.CharField(
        max_length=50,
        choices=SERVICE_CHOICES,
        default="Drinks"
        )
    phone = models.BigIntegerField()
    day = models.DateField(
        default=datetime.now
        )
    time = models.CharField(
        max_length=10,
        choices=TIME_CHOICES,
        default="12 PM")
    time_booked = models.DateTimeField(
        default=datetime.now,
        blank=True)

    def __str__(self):
        return f"{self.user.username} | day: {self.day} | time: {self.time}"

contact/models.py
# Create your models here.

# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Model for the contact item in the database


class Contact(models.Model):
    """
    A class for the Contact model
    """
    message_id = models.AutoField(primary_key=True)
    created_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="contact_user",
        null=True
        )
    name = models.CharField(
        max_length=50,
        null=True
        )
    email = models.EmailField(
        max_length=254,
        default=""
        )
    phone = PhoneNumberField(null=True)
    message = models.TextField()

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name

booking/forms.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django import forms
from crispy_forms.helper import FormHelper
from datetime import date
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from .models import TableBooking
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# The form for creating and editing a booking.


class BookingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

    def clean_day(self):
        day = self.cleaned_data['day']
        if day <= date.today():
            raise forms.ValidationError("Please select a future date.")
        return day

    class Meta:
        model = TableBooking
        fields = ('email', 'phone', 'day', 'time', 'service')
        widgets = {
            'day': forms.DateInput(attrs={'type': 'date'}),
        }

contact/forms.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django import forms
from crispy_forms.helper import FormHelper
from phonenumber_field.formfields import PhoneNumberField
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from .models import Contact
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# The contact form for the user to send a message to the business


class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

    phone = PhoneNumberField(widget=forms.TextInput(
        attrs={'placeholder': ('+441002003004')}))

    class Meta:
        model = Contact
        fields = (
            'name',
            'phone',
            'email',
            'message')

booking/views.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.shortcuts import render, redirect, reverse, get_object_or_404
from datetime import date, datetime, timedelta
from django.contrib import messages
from django.views import View
from django.core.exceptions import PermissionDenied

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from .models import *
from .forms import *
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


def index(request):
    return render(request, "index.html", {})


def user_panel(request):
    """
    Takes the user data and bookings.
    Displays to the user in the user panel template.
    """
    user = request.user
    bookings = TableBooking.objects.filter(user=user).order_by('day', 'time')
    return render(request, '../templates/user_panel.html', {
        'user': user,
        'bookings': bookings,
    })


def booking_new(request, booking_id=None):
    user = request.user
    instance = TableBooking()

    if booking_id:
        instance = get_object_or_404(TableBooking, pk=booking_id)

    booking_form = BookingForm(request.POST or None, instance=instance)

    if request.POST and booking_form.is_valid():
        booking = booking_form.save(commit=False)
        booking.user = user
        booking.save()
        messages.success(request, "New booking created!")
        return redirect('home')

    context = {
        'user': user,
        'booking_form': booking_form,
        'booking': instance
    }
    return render(request, 'booking_form.html', context)


def booking_edit(request, booking_id=None):
    user = request.user
    instance = TableBooking.objects.get(pk=booking_id)

    if instance.user != user:
        raise PermissionDenied()

    form = BookingForm(request.POST or None, instance=instance)

    if request.POST and form.is_valid():
        booking = form.save(commit=False)
        booking.user = user
        booking.save()
        messages.success(request, "Booking updated.")
        return redirect('booking:user-panel')

    context = {
        'user': user,
        'booking_form': form,
        'booking': instance
    }
    return render(request, 'booking_edit.html', context)


def booking_delete(request, id):
    user = request.user
    booking = get_object_or_404(TableBooking, pk=id)

    if booking.user != user:
        raise PermissionDenied()

    if request.method == 'POST':
        booking.user = user
        booking.delete()
        messages.success(
            request, "Booking deleted.")
        return redirect('home')
    context = {
        'booking': booking
    }
    return render(request, 'booking_delete.html', context)


def handle_permission_denied(request, exception):
    return render(request, '403.html', status=403)


# 403 handler
handler403 = handle_permission_denied

contact/views.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from .forms import ContactForm
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Gets user information.


def get_user_instance(request):
    """
    Retrieves user details if logged in.
    """

    user_email = request.user.email
    user = User.objects.filter(email=user_email).first()
    return user


# Displays the contact form for the user, autofills their email,
# Checks all data is valid before saving it.


class ContactMessage(View):
    """
    Displays the contact form if the user
    is registered and inserts the user email into the
    email field.
    """
    template_name = '../templates/contact.html'
    success_message = 'Your message has been sent.'

    def get(self, request, *args, **kwargs):
        """
        Retrieves users email and inputs into email input.
        """
        if request.user.is_authenticated:
            email = request.user.email
            contact_form = ContactForm(initial={'email': email})
        else:
            contact_form = ContactForm()
        return render(request, '../templates/contact.html',
                      {'contact_form': contact_form})

    def post(self, request):
        """
        Checks that the provided info is valid format
        and then posts to database.
        """
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            contact = contact_form.save(commit=False)
            contact.user = request.user
            contact.save()
            messages.success(
                request, "Your message has been sent.")
            return render(request, '../templates/contact.html')

        return render(request, '../templates/contact.html',
                      {'contact_form': contact_form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A Fantasy-Styled gaming tavern.">
    <meta name="keywords" content="board game, tavern, fantasy, gaming, food, D&D, MTG">
    <!--Google Fonts Link-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=MedievalSharp">
    <!--Font Awesome Script-->
    <script defer src="https://kit.fontawesome.com/749d4dd5a6.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!--style.css link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Favicon link-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <title>The Dragon's Flagon</title>
</head>

<body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-expand-lg navbg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://res.cloudinary.com/dbznc8xql/image/upload/c_scale,h_180,f_auto/v1675444756/dragons_flagon_logo_q9iwoa.jpg"
                    alt="Dragon Logo">
            </a>
            <a class="navbar-brand" href="{% url 'home' %}">
                <h1>The Dragon's Flagon</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                <ul class="navbar-nav navbar-left me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:user-panel' %}">User Panel</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav navbar-left me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                </ul>
                {% endif %}
                <ul class="navbar-nav navbar-right me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gallery' %}">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--Messages Start-->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success  alert-dismissible fade show text-center " role="alert">
        <h3 class="display-3">{{ message }}</h3>
        <button type="button" class="btn-close fs-1 position-absolute top-50 start-0 translate-middle-y"
            data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <!--Messages End-->
<main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
</main>
    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <div class="container text-center">
            <div class="row align-items-start">
                <div class="col">
                    <p class="m-0 text-start text-white">Created By: Stuart Wall <br>
                        <a target="blank" href="https://github.com/Clinelly">
                            <i class="fa-brands fa-square-github ms-3"></i>
                        </a>
                        <a target="blank" href="https://www.linkedin.com/in/swall289/">
                            <i class="fa-brands fa-linkedin ms-3"></i>
                        </a>
                    </p>
                </div>
                <div class="col">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fooddrink' %}">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'games' %}">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'events:calendar' %}">Events</a>
                        </li>
                    </ul>
                </div>
                <div class="col">
                    <p class="m-0 text-end text-white">Follow us: <br>
                        <a target="blank" href="https://www.facebook.com/dicetowergaming">
                            <i class="fab fa-facebook-square ms-3"></i>
                        </a>
                        <a target="blank" href="https://twitter.com/CriticalRole">
                            <i class="fab fa-twitter-square ms-3"></i>
                        </a>
                        <a target="blank" href="https://www.instagram.com/dicetowergaming/">
                            <i class="fab fa-instagram-square ms-3"></i>
                        </a>
                        <a target="blank" href="https://www.youtube.com/@GeekandSundry">
                            <i class="fab fa-youtube-square ms-3"></i>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!--Bootstrap JS Link-->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
    </script>
</body>

</html>

templates/bookingSubmit.html
<title>Session Booking</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}




{% if user.is_authenticated %}
<div class="row container-fluid d-flex align-items-center text-center bg-light mx-auto">
    <h1 class="text-center mt-3">Online Booking</h1>
</div>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black text-center m-5">
    <form method="post" action="{% url 'booking:submit-booking' %}" class="me-2 ms-2" required>
        {% csrf_token %}
        
        <!--input time-->
        <h3 class="text-center fPersian mt-4">Time:</h3>
        <div>
            <select class="form-select fs-3 text-center" name="time">
                {% for time in times %}
                <option value="{{ time }}">{{ time }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary text-white mt-3 fPersian">Submit</button>

    </form>
</div>

{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5">
    <h1 class="p-2  me-3">First Sign in!</h1>
    <a href="{% url 'account_login' %}" class="btn btn-primary text-white">Sign in</a>
</div>

{% endif %}


{% endblock %}

templates/delete_event.html
{% extends "base.html" %}
{% load static %}
<title>Delete Event</title>
{% block content %}

{% if user.is_superuser %}
<div class="row text-center text-white">
  <h2>Delete Event at the Dragon's Flagon</h2>
</div>
<div class="container text-center text-white">
  Title: {{ event.title}}
  <br>
  Description: {{ event.description }}
  <br>
  Start Time: {{ event.start_time }}
  <br>
  End Time: {{ event.end_time }}
</div>
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'events:calendar' %}">Return to Calendar </a>
</div>

<form action="{% url 'events:event_delete' event_id=event.id %}" method="post">
  {% csrf_token %}
  <table class="form form-table">
    <tr>
      <td colspan="1"><button type="submit" class="btn btn-info right"> Delete </button></td>
    </tr>

  </table>
</form>


{% else %}
<div class="container text-center text-white">
  <h2>Event Details</h2>
  Title: {{ event.title}}
  <br>
  Description: {{ event.description }}
  <br>
  Start Time: {{ event.start_time }}
  <br>
  End Time: {{ event.end_time }}
</div>

{% endif %}
{% endblock %}

templates/edit_event.html
{% extends "base.html" %}
<title>Edit Event</title>
{% load static %}
{% block content %}

{% if user.is_superuser %}
<div class="row text-center text-white">
    <h2>Edit Events at the Dragon's Flagon</h2>
</div>
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'events:calendar' %}">Return to Calendar </a>
</div>
  
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}
  
  
  <form method="post">
    {% csrf_token %}
    <table class="form form-table bg-danger border border-dark border-5">
      {{ form }}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
      <tr><td colspan="2"><a class="btn btn-info left" href="{% url 'events:event_delete' event_id=event.id %}"> Delete </a></td></tr>
    </table>
  </form>
  
  {% else %}
  <div class="container text-center text-white">
    <h2>Event Details</h2>
    Title: {{ event.title}}
    <br>
    Description: {{ event.description }}
    <br>
    Start Time: {{ event.start_time }}
    <br>
    End Time: {{ event.end_time }}
  </div>
  <div class="clearfix">
    <a class="btn btn-info left" href="{% url 'events:calendar' %}">Return to Calendar </a>
</div>
  {% endif %}
  
{%endblock%}

templates/index.html
{% extends "base.html" %}
{% load static %}
<title>Home</title>
{% block content %}

<!--Hero Image Container-->
<div id="hero-image" class="container-fluid">
    <img src="https://res.cloudinary.com/dbznc8xql/image/upload/f_auto/v1678369462/bar_smsovg.jpg"
        class="img-fluid mx-auto d-block" alt="The tavern interior">
</div>

<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <!-- Introduction Section-->
        <div class="col-lg-6 col-sm-10 text-center info-area border border-5 border-dark">
            <h2>Welcome to the Dragon's Flagon!</h2>
            <hr>
            <p>The closest place to Nerdvana you can get to on earth! 
            We are a cafe, lounge, bar, restaurant and gaming den all rolled into one!
            Packed to the rafters with comics and books; as well as a vast selection of table-top, card and board games - we have something for every geeky occasion.
            We serve a selection of great local drinks and adventurous cocktails, as well as food hearty enough to satisfy even Thor himself.
            <br>
            What are you waiting for? Book your table today or browse our calendar for one of our regular events!
            </p>
            <a class="btn btn-info" href="{% url 'booking:booking-form' %}">Book Your Table!</a>
            <a class="btn btn-info" href="{% url 'events:calendar' %}">View Our Events!</a>
            <hr>
            <p>Opening Hours:</p>
            <p><i class="fa-solid fa-clock"></i>
              Monday - Sunday: 9am - 12pm
            </p>
        </div>
    </div>
        <!--Public Post Section-->
    <div class="row row d-flex justify-content-center">
        <div class="col-lg-6 col-sm-10 review-area text-center border border-5 border-dark">
            <h2>What People Say About Us:</h2>
            <div class="row">
                {% for review in review_list %}
                <div class="col-lg-4 col-md-6 col-sm-8">
                    <div class="card">
                        <div class="card-body review-card">
                            Author: {{ review.author|safe }}
                            <br>
                            {{ review.title|safe }}
                            <hr>
                            {{ review.content|safe }}
                            <hr>
                            <p> {{review.created_on}} </p>
                            <div class="col-1">
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:6 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <a class="btn btn-info" href="{% url 'review_page' %}"> Leave a Review </a>
            {% endif %}
        </div>
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
    {%endblock%}

templates/new_event.html
{% extends "base.html" %}
<title>New Event</title>
{% load static %}
{% block content %}

<div class="row text-center text-white">
    <h2>Create Event at the Dragon's Flagon</h2>
</div>
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'events:calendar' %}"> Return to Calendar </a>
</div>
  
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}
  
  
  <form method="post">
    {% csrf_token %}
    <table class="form form-table bg-danger border border-dark border-5">
      {{ form }}
      {% if user.is_superuser %}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
      {% endif %}
    </table>
  </form>


{%endblock%}